#
# [ Database Configuration Section ]
#

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myTest?user=thinknear&password=
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9097
logging:
  level:
    org:
      hibernate:
        type: trace


